eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
logging:
  level:
    com:
      sagari:
        service:
          mapper: DEBUG
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9100
spring:
  application:
    name: sagari-notice-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123123!!0a
    url: jdbc:mysql://rm-uf68xva1989q98g721o.mysql.rds.aliyuncs.com:3306/sagari?useUnicode=true&characterEncoding=UTF-8
    username: sagari_apollo
swagger:
  base-package: com.sagari.service
  contact:
    email: 442982442@qq.com
    name: 魏梦鑫
  description: 通知服务接口，提供生成、标记已读、删除通知等功能
  terms-of-service-url: www.sagari.cn
  title: 通知服务接口
  version: 1.0
xxl:
  sso:
    redis:
      address: redis://xxl-sso:123123..0a@47.101.139.100:6379
      expire:
        minute: 30
